from exceptions.base import DataBaseException

