2025-02-22 22:06:04 - app - INFO - Логирование успешно настроено
2025-02-22 22:06:05 - middleware.error_handler - INFO - Входящий запрос: GET http://127.0.0.1:8000/docs
2025-02-22 22:06:05 - middleware.error_handler - INFO - Исходящий ответ: 200
2025-02-22 22:06:05 - middleware.error_handler - INFO - Входящий запрос: GET http://127.0.0.1:8000/openapi.json
2025-02-22 22:06:05 - middleware.error_handler - INFO - Исходящий ответ: 200
2025-02-22 22:06:39 - middleware.error_handler - INFO - Входящий запрос: GET http://127.0.0.1:8000/api/auth/test-logging
2025-02-22 22:06:39 - api.auth.router - INFO - Это info сообщение
2025-02-22 22:06:39 - api.auth.router - WARNING - Это warning сообщение
2025-02-22 22:06:39 - api.auth.router - ERROR - Это error сообщение: Тестовая ошибка
Traceback (most recent call last):
  File "C:\Users\sslinnn\Desktop\PartyFinder\api\auth\router.py", line 90, in test_logging
    raise ValueError("Тестовая ошибка")
ValueError: Тестовая ошибка
2025-02-22 22:06:39 - middleware.error_handler - INFO - Исходящий ответ: 200
2025-02-22 22:07:37 - app - INFO - Логирование успешно настроено
2025-02-22 22:08:39 - middleware.error_handler - INFO - Входящий запрос: POST http://localhost:8000/api/auth/login
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - select pg_catalog.version()
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - select current_schema()
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - show standard_conforming_strings
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.password, users.email, users.email_confirmed, users.is_active, users.is_superuser, users.first_name, users.last_name, users.created_at, users.updated_at 
FROM users 
WHERE users.email = $1::VARCHAR
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - [generated in 0.00282s] ('awdsdwa@mail.ru',)
2025-02-22 22:08:39 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-02-22 22:08:39 - middleware.error_handler - INFO - Исходящий ответ: 400
2025-02-22 22:09:37 - app - INFO - Логирование успешно настроено
2025-02-22 22:09:39 - app - INFO - Логирование успешно настроено
2025-02-22 22:09:45 - app - INFO - Логирование успешно настроено
2025-02-22 22:09:46 - middleware.error_handler - INFO - Входящий запрос: POST http://localhost:8000/api/auth/login
2025-02-22 22:09:46 - middleware.error_handler - INFO - Исходящий ответ: 400
